stages:
  - BuildFpm
  - BuildApache

image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


Build and push (TYPO3 6.2) (PHP 5.6) (FPM Alpine) image:
  stage: BuildFpm
  script:
    - docker build --build-arg PHP_IMAGE_TAG=0.1.0-php5.6-fpm-alpine --build-arg CRONTAB_DIRECTORY=/etc/crontabs -t crinis/typo3:6.2-php5.6-fpm-alpine -f 6.2/Dockerfile 6.2/
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:6.2-php5.6-fpm-alpine "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2-php5.6-fpm-alpine"; fi
    - docker push crinis/typo3:6.2-php5.6-fpm-alpine
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2-php5.6-fpm-alpine"; fi

Build and push (TYPO3 7.6) (PHP 7.1) (FPM Alpine) image:
  stage: BuildFpm
  script:
    - docker build --build-arg PHP_IMAGE_TAG=0.1.0-php7.1-fpm-alpine --build-arg CRONTAB_DIRECTORY=/etc/crontabs -t crinis/typo3:7.6-php7.1-fpm-alpine -f 7.6/Dockerfile 7.6/
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:7.6-php7.1-fpm-alpine "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6-php7.1-fpm-alpine"; fi
    - docker push crinis/typo3:7.6-php7.1-fpm-alpine
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6-php7.1-fpm-alpine"; fi

Build and push (TYPO3 8.7) (PHP 7.2) (FPM Alpine) image:
  stage: BuildFpm
  script:
    - docker build --build-arg PHP_IMAGE_TAG=0.1.0-php7.2-fpm-alpine --build-arg CRONTAB_DIRECTORY=/etc/crontabs -t crinis/typo3:8.7-php7.2-fpm-alpine -f 8.7/Dockerfile 8.7/
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:8.7-php7.2-fpm-alpine "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7-php7.2-fpm-alpine"; fi
    - docker push crinis/typo3:8.7-php7.2-fpm-alpine
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7-php7.2-fpm-alpine"; fi

Build and push (TYPO3 9.5) (PHP 7.2) (FPM Alpine) image:
  stage: BuildFpm
  script:
    - docker build --build-arg PHP_IMAGE_TAG=0.1.0-php7.2-fpm-alpine --build-arg CRONTAB_DIRECTORY=/etc/crontabs -t crinis/typo3:9.5-php7.2-fpm-alpine -f 9.5/Dockerfile 9.5/
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:9.5-php7.2-fpm-alpine "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5-php7.2-fpm-alpine"; fi
    - docker push crinis/typo3:9.5-php7.2-fpm-alpine
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5-php7.2-fpm-alpine"; fi


Build and push (TYPO3 6.2) (PHP 5.6) (Apache) image:
  stage: BuildApache
  script:
    - docker build -t crinis/typo3:6.2-php5.6-apache -f 6.2/Dockerfile 6.2/
    - docker tag crinis/typo3:6.2-php5.6-apache crinis/typo3:6.2
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:6.2-php5.6-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2-php5.6-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:6.2-php5.6-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2"; fi
    - docker push crinis/typo3:6.2-php5.6-apache
    - docker push crinis/typo3:6.2
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2-php5.6-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_6.2"; fi

Build and push (TYPO3 7.6) (PHP 7.1) (Apache) image:
  stage: BuildApache
  script:
    - docker build -t crinis/typo3:7.6-php7.1-apache -f 7.6/Dockerfile 7.6/
    - docker tag crinis/typo3:7.6-php7.1-apache crinis/typo3:7.6
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:7.6-php7.1-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6-php7.1-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:7.6-php7.1-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6"; fi
    - docker push crinis/typo3:7.6-php7.1-apache
    - docker push crinis/typo3:7.6
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6-php7.1-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_7.6"; fi

Build and push (TYPO3 8.7) (PHP 7.2) (Apache) image:
  stage: BuildApache
  script:
    - docker build -t crinis/typo3:8.7-php7.2-apache -f 8.7/Dockerfile 8.7/
    - docker tag crinis/typo3:8.7-php7.2-apache crinis/typo3:8.7
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:8.7-php7.2-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7-php7.2-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:8.7-php7.2-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7"; fi
    - docker push crinis/typo3:8.7-php7.2-apache
    - docker push crinis/typo3:8.7
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7-php7.2-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_8.7"; fi

Build and push (TYPO3 9.5) (PHP 7.2) (Apache) image:
  stage: BuildApache
  script:
    - docker build -t crinis/typo3:9.5-php7.2-apache -f 9.5/Dockerfile 9.5/
    - docker tag crinis/typo3:9.5-php7.2-apache crinis/typo3:9.5
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:9.5-php7.2-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5-php7.2-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker tag crinis/typo3:9.5-php7.2-apache "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5"; fi
    - docker tag crinis/typo3:9.5-php7.2-apache crinis/typo3:latest
    - docker push crinis/typo3:9.5-php7.2-apache
    - docker push crinis/typo3:9.5
    - docker push crinis/typo3:latest
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5-php7.2-apache"; fi
    - if [ ! -z ${CI_COMMIT_TAG+x} ]; then docker push "crinis/typo3:${CI_COMMIT_TAG}-typo3_9.5"; fi


after_script:
  - docker logout
