image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  IMAGE_REPOSITORY: "crinis/typo3"

before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://index.docker.io/v1/
  - apk update && apk add curl jq
  - >
    function get_minor_version() {
      TYPO3_MINOR_VERSION=$(basename $(curl -L --head -w '%{url_effective}' https://get.typo3.org/$1 2>/dev/null | tail -n1) .tar.gz)
      TYPO3_MINOR_VERSION=${TYPO3_MINOR_VERSION#"typo3_src-"}
      echo $TYPO3_MINOR_VERSION
    }
  - >
    function docker_tag_exists() {
      TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${DOCKER_HUB_USERNAME}'", "password": "'${DOCKER_HUB_PASSWORD}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
      EXISTS=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/$1/tags/?page_size=10000 | jq -r "[.results | .[] | .name == \"$2\"] | any")
      test $EXISTS = true
    }

build-6.2-php5.6-apache:
  variables:
    TYPO3_VERSION: "6.2"
    BASE_IMAGE_TAG: "5.6-apache"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY $TYPO3_MINOR_VERSION; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-6.2-php5.6-fpm-alpine:
  variables:
    TYPO3_VERSION: "6.2"
    BASE_IMAGE_TAG: "5.6-fpm-alpine"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY "${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}"; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-7.6-php7.1-apache:
  variables:
    TYPO3_VERSION: "7.6"
    BASE_IMAGE_TAG: "7.1-apache"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY $TYPO3_MINOR_VERSION; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-7.6-php7.1-fpm-alpine:
  variables:
    TYPO3_VERSION: "7.6"
    BASE_IMAGE_TAG: "7.1-fpm-alpine"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY "${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}"; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-8.7-php7.2-apache:
  variables:
    TYPO3_VERSION: "8.7"
    BASE_IMAGE_TAG: "7.2-apache"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY $TYPO3_MINOR_VERSION; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-8.7-php7.2-fpm-alpine:
  variables:
    TYPO3_VERSION: "8.7"
    BASE_IMAGE_TAG: "7.2-fpm-alpine"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY "${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}"; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-9.5-php7.2-apache:
  variables:
    TYPO3_VERSION: "9.5"
    BASE_IMAGE_TAG: "7.2-apache"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY $TYPO3_MINOR_VERSION; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

build-9.5-php7.2-fpm-alpine:
  variables:
    TYPO3_VERSION: "9.5"
    BASE_IMAGE_TAG: "7.2-fpm-alpine"
    BASE_IMAGE_TAG_VERSION: "0.2.0"
  script:
    - TYPO3_MINOR_VERSION=$(get_minor_version $TYPO3_VERSION)
    - >
      docker build -t ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG} \
        -t ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG} \
        --build-arg TYPO3_VERSION=${TYPO3_MINOR_VERSION} \
        --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}-${BASE_IMAGE_TAG_VERSION} \
        -f ${TYPO3_VERSION}/Dockerfile ${TYPO3_VERSION}/
    - docker push ${IMAGE_REPOSITORY}:${TYPO3_VERSION}-php${BASE_IMAGE_TAG}
    - > 
      if ! docker_tag_exists $IMAGE_REPOSITORY "${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}"; then
        docker push ${IMAGE_REPOSITORY}:${TYPO3_MINOR_VERSION}-php${BASE_IMAGE_TAG}
      fi

after_script:
  - docker logout
